export enum Feeling {
  JOYFUL = 'joyful',
  DOWN = 'down',
  ANXIOUS = 'anxious',
  CALM = 'calm',
  EXCITED = 'excited',
  FRUSTRATED = 'frustrated',
  LONELY = 'lonely',
  MOTIVATED = 'motivated',
  IRRITABLE = 'irritable',
  PEACEFUL = 'peaceful',
  TIRED = 'tired',
  HOPEFUL = 'hopeful',
  CONFIDENT = 'confident',
  STRESSED = 'stressed',
  CONTENT = 'content',
  DISAPPOINTED = 'disappointed',
  OPTIMISTIC = 'optimistic',
  RESTLESS = 'restless',
}
